input.onButtonPressed(Button.A, function () {
    for (let index = 0; index < 10; index++) {
        strip = neopixel.create(DigitalPin.P6, 24, NeoPixelMode.RGB)
        music.playTone(494, music.beat(BeatFraction.Whole))
        strip.showColor(neopixel.colors(NeoPixelColors.Red))
        music.playTone(440, music.beat(BeatFraction.Whole))
        strip.showColor(neopixel.colors(NeoPixelColors.Blue))
    }
})
input.onButtonPressed(Button.B, function () {
    for (let index = 0; index < 10; index++) {
        strip = neopixel.create(DigitalPin.P15, 24, NeoPixelMode.RGB)
        music.playTone(988, music.beat(BeatFraction.Half))
        strip.showColor(neopixel.colors(NeoPixelColors.Red))
        music.playTone(698, music.beat(BeatFraction.Half))
        strip.showColor(neopixel.colors(NeoPixelColors.Green))
    }
})
let strip: neopixel.Strip = null
basic.showString("Rayo Maqueen cachau")
basic.showLeds(`
    # # # # #
    # . # . #
    # # # # #
    . # # # .
    . # # # .
    `)
strip = neopixel.create(DigitalPin.P0, 24, NeoPixelMode.RGB)
music.playTone(330, music.beat(BeatFraction.Whole))
strip.showColor(neopixel.colors(NeoPixelColors.Blue))
music.playTone(330, music.beat(BeatFraction.Whole))
strip.showColor(neopixel.colors(NeoPixelColors.Red))
music.playTone(330, music.beat(BeatFraction.Whole))
strip.showColor(neopixel.colors(NeoPixelColors.Green))
music.playTone(262, music.beat(BeatFraction.Whole))
strip.showColor(neopixel.colors(NeoPixelColors.Blue))
music.playTone(330, music.beat(BeatFraction.Whole))
strip.showColor(neopixel.colors(NeoPixelColors.Red))
music.playTone(392, music.beat(BeatFraction.Whole))
strip.showColor(neopixel.colors(NeoPixelColors.Green))
music.playTone(392, music.beat(BeatFraction.Whole))
strip.showColor(neopixel.colors(NeoPixelColors.Blue))
music.playTone(262, music.beat(BeatFraction.Whole))
strip.showColor(neopixel.colors(NeoPixelColors.Red))
music.playTone(392, music.beat(BeatFraction.Whole))
strip.showColor(neopixel.colors(NeoPixelColors.Green))
music.playTone(330, music.beat(BeatFraction.Whole))
strip.showColor(neopixel.colors(NeoPixelColors.Blue))
music.playTone(440, music.beat(BeatFraction.Whole))
strip.showColor(neopixel.colors(NeoPixelColors.Red))
music.playTone(494, music.beat(BeatFraction.Whole))
strip.showColor(neopixel.colors(NeoPixelColors.Green))
music.playTone(440, music.beat(BeatFraction.Whole))
strip.showColor(neopixel.colors(NeoPixelColors.Blue))
music.playTone(392, music.beat(BeatFraction.Whole))
strip.showColor(neopixel.colors(NeoPixelColors.Red))
music.playTone(330, music.beat(BeatFraction.Whole))
strip.showColor(neopixel.colors(NeoPixelColors.Blue))
music.playTone(392, music.beat(BeatFraction.Whole))
strip.showColor(neopixel.colors(NeoPixelColors.Red))
music.playTone(440, music.beat(BeatFraction.Whole))
strip.showColor(neopixel.colors(NeoPixelColors.Green))
music.playTone(349, music.beat(BeatFraction.Whole))
strip.showColor(neopixel.colors(NeoPixelColors.Blue))
music.playTone(392, music.beat(BeatFraction.Whole))
strip.showColor(neopixel.colors(NeoPixelColors.Red))
music.playTone(330, music.beat(BeatFraction.Whole))
strip.showColor(neopixel.colors(NeoPixelColors.Green))
music.playTone(262, music.beat(BeatFraction.Whole))
strip.showColor(neopixel.colors(NeoPixelColors.Blue))
music.playTone(294, music.beat(BeatFraction.Whole))
strip.showColor(neopixel.colors(NeoPixelColors.Red))
music.playTone(494, music.beat(BeatFraction.Whole))
strip.showColor(neopixel.colors(NeoPixelColors.Green))
music.playTone(262, music.beat(BeatFraction.Whole))
strip.showColor(neopixel.colors(NeoPixelColors.Blue))
music.playTone(392, music.beat(BeatFraction.Whole))
strip.showColor(neopixel.colors(NeoPixelColors.Red))
music.playTone(330, music.beat(BeatFraction.Whole))
strip.showColor(neopixel.colors(NeoPixelColors.Green))
music.playTone(440, music.beat(BeatFraction.Whole))
strip.showColor(neopixel.colors(NeoPixelColors.Blue))
music.playTone(494, music.beat(BeatFraction.Whole))
strip.showColor(neopixel.colors(NeoPixelColors.Red))
music.playTone(440, music.beat(BeatFraction.Whole))
strip.showColor(neopixel.colors(NeoPixelColors.Green))
music.playTone(392, music.beat(BeatFraction.Whole))
strip.showColor(neopixel.colors(NeoPixelColors.Blue))
music.playTone(330, music.beat(BeatFraction.Whole))
strip.showColor(neopixel.colors(NeoPixelColors.Red))
music.playTone(392, music.beat(BeatFraction.Whole))
strip.showColor(neopixel.colors(NeoPixelColors.Green))
music.playTone(440, music.beat(BeatFraction.Whole))
strip.showColor(neopixel.colors(NeoPixelColors.Blue))
music.playTone(349, music.beat(BeatFraction.Whole))
strip.showColor(neopixel.colors(NeoPixelColors.Red))
music.playTone(392, music.beat(BeatFraction.Whole))
strip.showColor(neopixel.colors(NeoPixelColors.Green))
music.playTone(330, music.beat(BeatFraction.Whole))
strip.showColor(neopixel.colors(NeoPixelColors.Blue))
music.playTone(262, music.beat(BeatFraction.Whole))
strip.showColor(neopixel.colors(NeoPixelColors.Red))
music.playTone(294, music.beat(BeatFraction.Whole))
strip.showColor(neopixel.colors(NeoPixelColors.Green))
music.playTone(494, music.beat(BeatFraction.Whole))
strip.showColor(neopixel.colors(NeoPixelColors.Green))
basic.forever(function () {
	
})
