input.onButtonPressed(Button.A, function () {
    strip.showColor(neopixel.colors(NeoPixelColors.Red))
    basic.pause(1000)
    strip.showColor(neopixel.colors(NeoPixelColors.Blue))
    basic.pause(1000)
})
input.onButtonPressed(Button.B, function () {
    strip.showColor(neopixel.colors(NeoPixelColors.Blue))
    basic.pause(1000)
})
let strip: neopixel.Strip = null
basic.showString("Rayo Maqueen cachau")
basic.showLeds(`
    # # # # #
    # . # . #
    # # # # #
    . # # # .
    . # # # .
    `)
strip = neopixel.create(DigitalPin.P0, 24, NeoPixelMode.RGB)
basic.forever(function () {
    music.playTone(330, music.beat(BeatFraction.Whole))
    strip.showColor(neopixel.colors(NeoPixelColors.Blue))
    music.playTone(330, music.beat(BeatFraction.Whole))
    strip.showColor(neopixel.colors(NeoPixelColors.Red))
    music.playTone(330, music.beat(BeatFraction.Whole))
    strip.showColor(neopixel.colors(NeoPixelColors.Green))
    music.playTone(262, music.beat(BeatFraction.Whole))
    strip.showColor(neopixel.colors(NeoPixelColors.Blue))
    music.playTone(330, music.beat(BeatFraction.Whole))
    strip.showColor(neopixel.colors(NeoPixelColors.Red))
    music.playTone(392, music.beat(BeatFraction.Whole))
    strip.showColor(neopixel.colors(NeoPixelColors.Green))
    music.playTone(392, music.beat(BeatFraction.Whole))
    strip.showColor(neopixel.colors(NeoPixelColors.Blue))
    music.playTone(262, music.beat(BeatFraction.Whole))
    strip.showColor(neopixel.colors(NeoPixelColors.Red))
    music.playTone(392, music.beat(BeatFraction.Whole))
    strip.showColor(neopixel.colors(NeoPixelColors.Green))
    music.playTone(330, music.beat(BeatFraction.Whole))
    strip.showColor(neopixel.colors(NeoPixelColors.Blue))
    music.playTone(440, music.beat(BeatFraction.Whole))
    strip.showColor(neopixel.colors(NeoPixelColors.Red))
    music.playTone(494, music.beat(BeatFraction.Whole))
    strip.showColor(neopixel.colors(NeoPixelColors.Green))
    music.playTone(440, music.beat(BeatFraction.Whole))
    strip.showColor(neopixel.colors(NeoPixelColors.Blue))
    music.playTone(392, music.beat(BeatFraction.Whole))
    strip.showColor(neopixel.colors(NeoPixelColors.Red))
    music.playTone(330, music.beat(BeatFraction.Whole))
    strip.showColor(neopixel.colors(NeoPixelColors.Blue))
    music.playTone(392, music.beat(BeatFraction.Whole))
    strip.showColor(neopixel.colors(NeoPixelColors.Red))
    music.playTone(440, music.beat(BeatFraction.Whole))
    strip.showColor(neopixel.colors(NeoPixelColors.Green))
    music.playTone(349, music.beat(BeatFraction.Whole))
    strip.showColor(neopixel.colors(NeoPixelColors.Blue))
    music.playTone(392, music.beat(BeatFraction.Whole))
    strip.showColor(neopixel.colors(NeoPixelColors.Red))
    music.playTone(330, music.beat(BeatFraction.Whole))
    strip.showColor(neopixel.colors(NeoPixelColors.Green))
    music.playTone(262, music.beat(BeatFraction.Whole))
    strip.showColor(neopixel.colors(NeoPixelColors.Blue))
    music.playTone(294, music.beat(BeatFraction.Whole))
    strip.showColor(neopixel.colors(NeoPixelColors.Red))
    music.playTone(494, music.beat(BeatFraction.Whole))
    strip.showColor(neopixel.colors(NeoPixelColors.Green))
    music.playTone(262, music.beat(BeatFraction.Whole))
    strip.showColor(neopixel.colors(NeoPixelColors.Blue))
    music.playTone(392, music.beat(BeatFraction.Whole))
    strip.showColor(neopixel.colors(NeoPixelColors.Red))
    music.playTone(330, music.beat(BeatFraction.Whole))
    strip.showColor(neopixel.colors(NeoPixelColors.Green))
    music.playTone(440, music.beat(BeatFraction.Whole))
    strip.showColor(neopixel.colors(NeoPixelColors.Blue))
    music.playTone(494, music.beat(BeatFraction.Whole))
    strip.showColor(neopixel.colors(NeoPixelColors.Red))
    music.playTone(440, music.beat(BeatFraction.Whole))
    strip.showColor(neopixel.colors(NeoPixelColors.Green))
    music.playTone(392, music.beat(BeatFraction.Whole))
    strip.showColor(neopixel.colors(NeoPixelColors.Blue))
    music.playTone(330, music.beat(BeatFraction.Whole))
    strip.showColor(neopixel.colors(NeoPixelColors.Red))
    music.playTone(392, music.beat(BeatFraction.Whole))
    strip.showColor(neopixel.colors(NeoPixelColors.Green))
    music.playTone(440, music.beat(BeatFraction.Whole))
    strip.showColor(neopixel.colors(NeoPixelColors.Blue))
    music.playTone(349, music.beat(BeatFraction.Whole))
    strip.showColor(neopixel.colors(NeoPixelColors.Red))
    music.playTone(392, music.beat(BeatFraction.Whole))
    strip.showColor(neopixel.colors(NeoPixelColors.Green))
    music.playTone(330, music.beat(BeatFraction.Whole))
    strip.showColor(neopixel.colors(NeoPixelColors.Blue))
    music.playTone(262, music.beat(BeatFraction.Whole))
    strip.showColor(neopixel.colors(NeoPixelColors.Red))
    music.playTone(294, music.beat(BeatFraction.Whole))
    strip.showColor(neopixel.colors(NeoPixelColors.Green))
    music.playTone(494, music.beat(BeatFraction.Whole))
    strip.showColor(neopixel.colors(NeoPixelColors.Green))
})
